name: Benchmark PR

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

env:
  UV_VERSION: "0.7.4"

jobs:
  benchmark_pr_branch:
    name: Continuous Benchmarking PRs with Bencher
    # DO NOT REMOVE: For handling Fork PRs
    if: |
      github.event_name == 'pull_request' &&
      github.event.pull_request.head.repo.full_name == github.repository &&
      !startsWith(github.event.pull_request.head.ref, 'dependabot/')
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: true

      - name: Set up bencher
        uses: bencherdev/bencher@main

      - name: Set up Just
        uses: extractions/setup-just@v3

      - name: Track PR Benchmarks with Bencher
        run: |
          just bench_compare \
              --token '${{ secrets.BENCHER_API_TOKEN }}' \
              --branch "$GITHUB_HEAD_REF" \
              --start-point "$GITHUB_BASE_REF" \
              --start-point-hash '${{ github.event.pull_request.base.sha }}' \
              --start-point-clone-thresholds \
              --start-point-reset \
              --testbed Linux \
              --github-actions '${{ secrets.GITHUB_TOKEN }}'
