name: Benchmark PR

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

env:
  BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
  UV_VERSION: "0.6.6"

jobs:
  benchmark_pr_branch:
    name: Continuous Benchmarking PRs with Bencher
    # DO NOT REMOVE: For handling Fork PRs
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: true

      - name: Set up bencher
        uses: bencherdev/bencher@main

      - name: Set up Just
        uses: extractions/setup-just@v3

      - name: Track PR Benchmarks with Bencher
        run: |
          just bench_upload \
          --branch "$GITHUB_HEAD_REF" \
          --start-point "$GITHUB_BASE_REF" \
          --start-point-hash '${{ github.event.pull_request.base.sha }}' \
          --start-point-clone-thresholds \
          --start-point-reset \
          --testbed Linux \
          --err \
          --github-actions '${{ secrets.GITHUB_TOKEN }}'
