name: Benchmark PR

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

env:
  UV_VERSION: "0.7.4"

jobs:
  benchmark_pr_branch:
    name: Continuous Benchmarking PRs with Bencher
    # DO NOT REMOVE: For handling Fork PRs
    if: |
      github.event_name == 'pull_request' &&
      github.event.pull_request.head.repo.full_name == github.repository &&
      !startsWith(github.event.pull_request.head.ref, 'dependabot/')
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # We need to install llvm due to the way that we're pulling in the
      # selene-hugr-qis-compiler dependency for testing. Since we use an
      # unreleased version for testing, and have to compile it ourselves.
      #
      # Once the released version points to the correct versions of tket, we can
      # use the released version and drop this from CI.
      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "14.0"
      - name: Set LLVM_SYS_140_PREFIX
        run: echo "LLVM_SYS_140_PREFIX=${{ env.LLVM_PATH }}" >> $GITHUB_ENV

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: true

      - name: Set up bencher
        uses: bencherdev/bencher@main

      - name: Set up Just
        uses: extractions/setup-just@v3

      - name: Track PR Benchmarks with Bencher
        run: |
          just bench_compare \
              --token '${{ secrets.BENCHER_API_TOKEN }}' \
              --branch "$GITHUB_HEAD_REF" \
              --start-point "$GITHUB_BASE_REF" \
              --start-point-hash '${{ github.event.pull_request.base.sha }}' \
              --start-point-clone-thresholds \
              --start-point-reset \
              --testbed Linux \
              --github-actions '${{ secrets.GITHUB_TOKEN }}'
